// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201212024141_cambio_adjunto")]
    partial class cambio_adjunto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Monografico.Models.AdjuntoMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Ruta")
                        .HasColumnName("ruta")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("adjuntoMaterial");
                });

            modelBuilder.Entity("Monografico.Models.Calificaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("EstudianteId")
                        .HasColumnName("Estudiante_Id")
                        .HasColumnType("int");

                    b.Property<int>("ModuloId")
                        .HasColumnName("Modulo_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ModuloId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Monografico.Models.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Campus_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CampusCodigo")
                        .IsRequired()
                        .HasColumnName("Campus_Codigo")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("CampusNombre")
                        .IsRequired()
                        .HasColumnName("Campus_Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("LocalidadId")
                        .HasColumnName("Localidad_Id")
                        .HasColumnType("int");

                    b.HasKey("CampusId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Campus");
                });

            modelBuilder.Entity("Monografico.Models.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Carrera_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CampusId")
                        .HasColumnName("Campus_Id")
                        .HasColumnType("int");

                    b.Property<string>("CarreraCodigo")
                        .IsRequired()
                        .HasColumnName("Carrera_Codigo")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("CarreraNombre")
                        .IsRequired()
                        .HasColumnName("Carrera_Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("EscuelaId")
                        .HasColumnName("Escuela_Id")
                        .HasColumnType("int");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("FacultadId")
                        .HasColumnName("Facultad_Id")
                        .HasColumnType("int");

                    b.HasKey("CarreraId");

                    b.HasIndex("CampusId");

                    b.HasIndex("EscuelaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("FacultadId");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("Monografico.Models.Empleado", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Salario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(13, 2)")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Codigo");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Monografico.Models.Escuela", b =>
                {
                    b.Property<int>("EscuelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Escuela_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CampusId")
                        .HasColumnName("Campus_Id")
                        .HasColumnType("int");

                    b.Property<string>("EscuelaCodigo")
                        .IsRequired()
                        .HasColumnName("Escuela_Codigo")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("EscuelaNombre")
                        .IsRequired()
                        .HasColumnName("Escuela_Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("FacultadId")
                        .HasColumnName("Facultad_Id")
                        .HasColumnType("int");

                    b.HasKey("EscuelaId");

                    b.HasIndex("CampusId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("FacultadId");

                    b.ToTable("Escuela");
                });

            modelBuilder.Entity("Monografico.Models.Estado", b =>
                {
                    b.Property<string>("EstadoId")
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("EstadoNombre")
                        .IsRequired()
                        .HasColumnName("Estado_Nombre")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.HasKey("EstadoId");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Monografico.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("Monografico.Models.Facultad", b =>
                {
                    b.Property<int>("FacultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Facultad_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CampusId")
                        .HasColumnName("Campus_Id")
                        .HasColumnType("int");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("FacultadCodigo")
                        .IsRequired()
                        .HasColumnName("Facultad_Codigo")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("FacultadNombre")
                        .IsRequired()
                        .HasColumnName("Facultad_Nombre")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("FacultadId");

                    b.HasIndex("CampusId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Facultad");
                });

            modelBuilder.Entity("Monografico.Models.Localidad", b =>
                {
                    b.Property<int>("LocalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Localidad_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("LocalidadNombre")
                        .IsRequired()
                        .HasColumnName("Localidad_Nombre")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("LocalidadId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("Monografico.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnName("fecha_fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnName("fecha_inicio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdAdjunto")
                        .HasColumnName("id_adjunto")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesor")
                        .HasColumnName("id_Profesor")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnName("imagen")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int>("ServicioId")
                        .HasColumnName("Servicio_Id")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnName("titulo")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdAdjunto");

                    b.HasIndex("IdProfesor");

                    b.HasIndex("ServicioId");

                    b.ToTable("Modulo");
                });

            modelBuilder.Entity("Monografico.Models.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('A')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnName("Usuario_Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("Rol_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Rol_Id")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Codigo");

                    b.HasIndex("EstadoId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Monografico.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("Monografico.Models.Servicio", b =>
                {
                    b.Property<int>("Servicio_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Servicio_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Campus_Id")
                        .HasColumnName("Campus_Id")
                        .HasColumnType("int");

                    b.Property<int>("Carrera_Id")
                        .HasColumnName("Carrera_Id")
                        .HasColumnType("int");

                    b.Property<int>("Escuela_Id")
                        .HasColumnName("Escuela_Id")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Id")
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('I')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("Facultad_Id")
                        .HasColumnName("Facultad_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Usuario_Codigo")
                        .HasColumnName("Usuario_Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Servicio_Codigo")
                        .IsRequired()
                        .HasColumnName("Servicio_Codigo")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<decimal?>("Servicio_Costo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Servicio_Costo")
                        .HasColumnType("decimal(12, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Servicio_Descripcion")
                        .IsRequired()
                        .HasColumnName("Servicio_Descripcion")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Servicio_FechaCierre")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Servicio_FechaCierre")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('')");

                    b.Property<DateTime?>("Servicio_FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Servicio_FechaInicio")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('')");

                    b.Property<int>("TipoServicio_Id")
                        .HasColumnName("TipoServicio_Id")
                        .HasColumnType("int");

                    b.HasKey("Servicio_Id");

                    b.HasIndex("Campus_Id");

                    b.HasIndex("Carrera_Id");

                    b.HasIndex("Escuela_Id");

                    b.HasIndex("Estado_Id");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("Monografico.Models.TipoServicio", b =>
                {
                    b.Property<int>("TipoServicioId")
                        .HasColumnName("TipoServicio_Id")
                        .HasColumnType("int");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Estado_Id")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('A')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("TipoServicioDescripcion")
                        .IsRequired()
                        .HasColumnName("TipoServicio_Descripcion")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("TipoServicioId");

                    b.HasIndex("EstadoId");

                    b.ToTable("TipoServicio");
                });

            modelBuilder.Entity("Monografico.Models.Usuario", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Codigo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Monografico.Models.AdjuntoMaterial", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("AdjuntoMaterial")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_adjuntoMaterialEstado")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Calificaciones", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Calificaciones")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_CalificacionesEstado")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Estudiante", "Estudiante")
                        .WithMany("Calificaciones")
                        .HasForeignKey("EstudianteId")
                        .HasConstraintName("FK_CalificacionEstudiantes")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Modulo", "Modulo")
                        .WithMany("Calificaciones")
                        .HasForeignKey("ModuloId")
                        .HasConstraintName("FK_CalficaionesModulos")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Campus", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Campus")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Campus_Estado")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Localidad", "Localidad")
                        .WithMany("Campus")
                        .HasForeignKey("LocalidadId")
                        .HasConstraintName("FK_Campus_Localidad")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Carrera", b =>
                {
                    b.HasOne("Monografico.Models.Campus", "Campus")
                        .WithMany("Carrera")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK_Carrera_Campus")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Escuela", "Escuela")
                        .WithMany("Carrera")
                        .HasForeignKey("EscuelaId")
                        .HasConstraintName("FK_Carrera_Escuela")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Carrera")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Carrera_Estado")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Facultad", "Facultad")
                        .WithMany("Carrera")
                        .HasForeignKey("FacultadId")
                        .HasConstraintName("FK_Carrera_Facultad")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Escuela", b =>
                {
                    b.HasOne("Monografico.Models.Campus", "Campus")
                        .WithMany("Escuela")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK_Escuela_Campus")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Escuela")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Escuela_Estado")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Facultad", "Facultad")
                        .WithMany("Escuela")
                        .HasForeignKey("FacultadId")
                        .HasConstraintName("FK_Escuela_Facultad")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Facultad", b =>
                {
                    b.HasOne("Monografico.Models.Campus", "Campus")
                        .WithMany("Facultad")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK_Facultad_Campus")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Facultad")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Facultad_Estado")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Localidad", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Localidad")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Localidad_Estado")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Modulo", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Modulo")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_ModuloEstado")
                        .IsRequired();

                    b.HasOne("Monografico.Models.AdjuntoMaterial", "IdAdjuntoNavigation")
                        .WithMany("Modulo")
                        .HasForeignKey("IdAdjunto")
                        .HasConstraintName("FK_ModuloAdjunto");

                    b.HasOne("Monografico.Models.Profesor", "IdProfesorNavigation")
                        .WithMany("Modulo")
                        .HasForeignKey("IdProfesor")
                        .HasConstraintName("FK_ModuloProfesor")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Servicio", "Servicio")
                        .WithMany("Modulo")
                        .HasForeignKey("ServicioId")
                        .HasConstraintName("FK_Modulo_Servicio")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Usuario", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Usuario")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Usuario_Estado")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Profesor", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Profesor")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_ProfesorEstado")
                        .IsRequired();
                });

            modelBuilder.Entity("Monografico.Models.Servicio", b =>
                {
                    b.HasOne("Monografico.Models.Campus", "Campus")
                        .WithMany("Servicio")
                        .HasForeignKey("Campus_Id")
                        .HasConstraintName("FK_Servicio_Campus")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Carrera", "Carrera")
                        .WithMany("Servicio")
                        .HasForeignKey("Carrera_Id")
                        .HasConstraintName("FK_Servicio_Carrera")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Escuela", "Escuela")
                        .WithMany("Servicio")
                        .HasForeignKey("Escuela_Id")
                        .HasConstraintName("FK_Servicio_Escuela")
                        .IsRequired();

                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("Servicio")
                        .HasForeignKey("Estado_Id")
                        .HasConstraintName("FK_Servicio_Estado");
                });

            modelBuilder.Entity("Monografico.Models.TipoServicio", b =>
                {
                    b.HasOne("Monografico.Models.Estado", "Estado")
                        .WithMany("TipoServicio")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_TipoServicio_Estado")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
